### ISSUE TITLE
是不是已经失效了？

### ISSUE THREAD

**Issue by JasinYip** [xyuanmu/parseiqiyi#1]
一直提示获取失败

**Comment by xyuanmu** [comment]
前置代理失效了，如果本机搭建环境或者服务器在国内可以清空iqiyi.class.php第5行冒号里的地址。

``` php
    const PROXY = "";    
```

**Comment by JasinYip** [comment]
我是在你提供的测试链接里试的 :cry: …… http://yuanmu.000webhost.cn/iqiyi/

**Comment by xyuanmu** [comment]
@JasinYip 因为一直都是本地获取所以没有注意服务器上的代码，代理已经更新过了 :smiley:
