### ISSUE TITLE
win环境下如何操作呢

### ISSUE THREAD

**Issue by Vicyyw** [xyuanmu/parseiqiyi#3]
大神，本人初次接触，很多都不懂。你的教程里面第一步说是上传服务器，是怎么上传呢。第二步打开php文件，是直接点进去编辑吗，在哪个地方输入url呢？配置php对我来说还是比较难得，希望是上传服务器，但我用的是win8···请教

**Comment by xyuanmu** [comment]
上传服务器，服务器有ftp帐户的话用ftp工具上传，如FlashFXP。上传index.php和iqiyi.class.php到同一个目录，如果是根目录，就直接打开服务器绑定的域名，如果是子目录如 /htdocs/iqiyi 或者 /WWW/iqiyi 就打开域名后面加上 /iqiyi，比如：http://yuanmu.000webhost.cn/iqiyi/ 就可以了。
爱奇艺隔段时间会更新enc_key，更新的时候替换新的iqiyi.class.php即可。

**Comment by Vicyyw** [comment]
大神，服务器是购买的或者需要自己创建的吧，我没有服务器，当然也就没有ftp帐号，那么是不是就只能走构建php环境这条路走了？
另外，我下载了phpStudy，看说明说是傻瓜式的，安装后就能构建php环境了，然后该怎么打开index.php，直接拖到php软件里面还是双击呢。
感觉php对没入门的我来说挺复杂的，但想学习。可以再解释一下吗

**Comment by Vicyyw** [comment]
大神，经过测试，发现与ip地址有关。我在国外，将ip地址调回国内就能进行全高清下载。
不过如果以后爱奇艺更新了key，parseiqiyi的iqiyi.class.php大神也会更新的吧。
那对you-get来说会有影响吗？因为我今天用猎豹浏览器安装了hack-iqiyi，发现并没有输出key，不知道跟我的32位XP系统有无关系

**Comment by xyuanmu** [comment]
有空会检查爱奇艺key，若发现更新了会同步更新iqiyi.class，至于 you-get，如果作者没及时更新，手动修改 you-get\src\you_get\extractors，iqiyi.py，48行 salt = '6ab6d0280511493ba85594779759d4ed'。
XP下测试过可以正常输出key，换一个浏览器试试。

**Comment by shanmm** [comment]
http://yuanmu.000webhost.cn/iqiyi
这个网址不行了？提示：未解析到1080P格式的视频！其他格式的也不行

**Comment by Vicyyw** [comment]
可以用的，跟网络环境，系统都有关系

---

谢谢大神，明白啦，回复晚了，见谅哈

**Comment by shanmm** [comment]
楼主可以将一下步骤吗

**Comment by xyuanmu** [comment]
@shanmm 爱奇艺开始限制IP了，那个测试的地址在海外，没加国内代理所以解析不了某些视频或者没有1080P。

如果你在墙内可以本机搭建一个php环境：
到[这里下载phpStudy](http://www.phpstudy.net/a.php/208.html)，Windows系统建议下载phpStudyLite。下载后解压运行程序，自动解压到一个地方，如：D:\phpStudy，解压好后运行phpStudy，点击启动，看到Apache和MySQL都是绿色，到浏览器输入 [http://localhost/phpinfo.php](http://localhost/phpinfo.php) ，如果出现一个页面说明成功了。然后下载 parseiqiyi 解压index.php和iqiyi.class.php到D:\phpStudy\WWW，在浏览器输入 [http://localhost](http://localhost) 就能看到解析页面了。

**Comment by shanmm** [comment]
@xyuanmu 嗯，我本地有wampserver，所以我打开index.php也看到了解析的页面，可是无论怎么都不能解析，我在国内。
提示这个，也看不懂，哎
好像是说没有定义function curl_init() in 
- ( ! ) Fatal error: Call to undefined function curl_init() in C:\wamp\www\php_urls\iqiyi.class.php on line 26
  Call Stack
  #   Time    Memory  Function    Location
  1   0.0006  268768  {main}( )   ..\index.php:0
  2   0.0016  342336  debug( )    ..\index.php:58
  3   0.0016  342384  Iqiyi::parse( ) ..\index.php:29
  4   0.0016  342448  Iqiyi::_cget( ) ..\iqiyi.class.php:9

**Comment by xyuanmu** [comment]
@shanmm curl扩展没开，打开php.ini，将 extension=php_curl.dll 前面的分号去掉，重启。如果还不行，谷歌或百度：Call to undefined function curl_init() 找解决方法

**Comment by shanmm** [comment]
@xyuanmu 嗯嗯，非常感谢，我去试试

**Comment by shanmm** [comment]
@xyuanmu xx谢谢，经过多次测试，终于弄好了，太感谢啦

**Comment by Jztsctl** [comment]
正常的视频可以解析了，是不是不支持vip视频呢！
要求有点高了，嘻嘻...
最近超级火爆的 太阳的后裔 凡事最新出的带有vip标识的视频都无法解析?

还有那个key我电脑无法生成，是不是等到它更新的时候我就无法解析任何视频了...
运行那个hack-iqiyi.bat后出现patch.exe已停止工作
cmd那个窗口出现
Downloading the page http://www.iqiyi.com/v_19rroonq48.html, please wait...
swf url is http://www.iqiyi.com/common/flashplayer/20160307/1335f98c2359.swf
patching file `Zombie.class.asasm'
Assertion failed: hunk, file patch.c, line 321

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Patch succeeded!
Serving HTTP on 127.0.0.1 port 8036 ...
但是我网页上面怎么播放视频也无法出现key丫
求救大神，帮忙解决...

**Comment by xyuanmu** [comment]
@Jztsctl vip视频无法解析，网上查了下出现的错误，有可能是vc++ 运行库的问题，你安装试试：https://www.microsoft.com/zh-CN/download/details.aspx?id=26347

**Comment by Jztsctl** [comment]
@xyuanmu 我卸载vc++ 安装你那个版本的还是已停止运行，崩溃...

**Comment by xyuanmu** [comment]
@Jztsctl 你按以下方法操作：
1. 到tool目录双击运行patch.exe 看有什么提示，估计跟CMD窗口的一样
2. 在开始菜单输入“事件查看器”，打开，展开 Windows 日志 - 应用程序
3. 把红色bug的事件内容粘贴或者截图传上来

**Comment by Jztsctl** [comment]
直接打开patch.exe 弹出cmd窗口，窗口内什么也没有...
常规：
错误应用程序名称: patch.exe，版本: 0.0.0.0，时间戳: 0x382892a0
错误模块名称: msvcrt.dll，版本: 7.0.7600.16385，时间戳: 0x4a5bda6f
异常代码: 0x40000015
错误偏移量: 0x00066804
错误进程 ID: 0xc10
错误应用程序启动时间: 0x01d17a934f774c9c
错误应用程序路径: C:\Users\张涛\Desktop\应用程序\爱奇艺解析\key\hack-iqiyi-master\tool\patch.exe
错误模块路径: C:\Windows\system32\msvcrt.dll
报告 ID: 8d2638dc-e686-11e5-b08b-0c8bfd2151f0
详细信息：
- System 
  - Provider 
  
  [ Name]  Application Error 
  - EventID 1000 
  
  [ Qualifiers]  0 
  
  Level 2 
  
  Task 100 
  
  Keywords 0x80000000000000 
  - TimeCreated 
  
  [ SystemTime]  2016-03-10T06:08:48.000000000Z 
  
  EventRecordID 88761 
  
  Channel Application 
  
  Computer 张涛-PC 
  
  Security 
- EventData 
  
  patch.exe 
  0.0.0.0 
  382892a0 
  msvcrt.dll 
  7.0.7600.16385 
  4a5bda6f 
  40000015 
  00066804 
  c10 
  01d17a934f774c9c 
  C:\Users\张涛\Desktop\应用程序\爱奇艺解析\key\hack-iqiyi-master\tool\patch.exe 
  C:\Windows\system32\msvcrt.dll 
  8d2638dc-e686-11e5-b08b-0c8bfd2151f0

**Comment by xyuanmu** [comment]
@Jztsctl 
出现这种问题，要么是程序有问题，要么系统有问题，这个patch.exe虽然比较旧但在我这里32位64位系统都能良好运行，你系统是ghost版本的吗？
可尝试的方法：到网上下载其他版本的 msvcrt.dll，重命名 C:\Windows\system32\ 目录下的 msvcrt.dll，然后将下载的 msvcrt.dll 放到system32目录。

**Comment by Jztsctl** [comment]
我用的是msdn的原版系统，不是ghost的~
等我回家，我试试win10怎么样吧，办公电脑装太多烂七八糟的软件了...
谢谢你...

**Comment by Jztsctl** [comment]
@xyuanmu 
我用的是msdn的原版系统，不是ghost的~
等我回家，我试试win10怎么样吧，办公电脑装太多烂七八糟的软件了...
谢谢你...
